---
services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="mongodb_version=2.6"
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="mongodb_version=3.0"
    - DOCKER_IMAGE=sebastienelet/docker-ubuntu1404-ansible DOCKER_INIT=/sbin/init ROLE_OPTIONS="mongodb_version=3.2"

before_install:
  - make docker-pull

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
